title: "agudeloromero.github.io"
description: "Patricia's personal website"

#layout
show_socail: true
external:
  -{title:Mail, icon:envelope, url: mailto:"Patricia.AgudeloRomero@gmail.com"}


plugins:
  - jekyll-maps
  
maps:
  google:
    api_key: <AIzaSyBxHli2qb0K5qso3jxUfoONp4pQgnQ4_Ys>
    
    location:
      latitude: -31.96928384758674
      longitude: 115.81716645638366
